# Generated by Django 4.1.6 on 2023-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_balance_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=3000, verbose_name='URL картинки'),
        ),
    ]
