# Generated by Django 4.1.6 on 2023-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
