# Generated by Django 4.1.6 on 2023-03-17 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_basket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть из 10 цифр, начиная с '7'.", regex='^7\\d{9}$')], verbose_name='Телефонный номер')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('product', models.ManyToManyField(blank=True, related_name='orders', to='webapp.product')),
            ],
        ),
    ]
