# Generated by Django 4.1.6 on 2023-03-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
